### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [XYunknown/i3status-rust#1]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by XYunknown** [comment]
No, it is completely unnessesary and only in there because I forgot to clean the dependencys up. Thanks for the reminder :) Fixed in https://github.com/XYunknown/i3status-rust/commit/e8fec710207ae716fe7d860108b695b26a76069c
